### ISSUE TITLE
webservices with static documents in ${config.stateDir}/www

### ISSUE THREAD

**Issue by qknight** [nixcloud/nixcloud-webservices#14]
# motivation

* `static-darkhttpd` and `static-nginx` should have an example index.html (and also for documents created by the user later on) served inside a `www` directory which should be created inside `${config.stateDir}`.
* `leaps`: create example document with text so that when the user visits the webservice for the first time sees something to edit instead of having to add this manually

for both `static-darkhttpd` and `static-nginx` the `test.nix` uses hardcoded values in the test:

see https://raw.githubusercontent.com/nixcloud/nixcloud-webservices/master/modules/web/services/static-darkhttpd/test.nix

**Comment by aszlig** [comment]
@qknight: Should this only be for the tests or for the actual production setup?

**Comment by qknight** [comment]
@aszlig this new concept should be for **production** as it makes sense for supporting legacy services.

**Comment by aszlig** [comment]
@qknight: Do the commits that reference this issue also address the issue?

**Comment by qknight** [comment]
these patches are very helpful, thanks
