### ISSUE TITLE
Too long group names

### ISSUE THREAD

**Issue by leenaars** [nixcloud/nixcloud-webservices#20]
After an intended upgrade to NixOS 18.03, group names appear to face new restrictions. The autogenerated names for webservices should be probably capped in some way:

`Group name 'leaps-demo-webserver' is longer than 16 characters which is not allowed!'`

**Comment by aszlig** [comment]
@leenaars: This issue will be solved once https://github.com/NixOS/nixpkgs/pull/38548 lands in `release-18.03` and `master`. I've pushed the fix to `staging` and `staging-18.03` because it's a mass-rebuild. Once the next staging merge is done upstream the error will be gone.

**Comment by qknight** [comment]
@leenaars closing this as it should be solved already. if not please reopen
