### ISSUE TITLE
The option `nixcloud.email.enableACME` does not exist.

### ISSUE THREAD

**Issue by erictapen** [nixcloud/nixcloud-webservices#29]
It's described in [here](https://github.com/nixcloud/nixcloud-webservices/blob/master/documentation/nixcloud.email.md).

My `nixcloud-webservices` checkout is 41616c7532965d72b2f67d95fb6121f798953293.

**Comment by qknight** [comment]
should be 'nixcloud.email.enableTLS` now as the option was renamed but the nixos renaming convention wasn't yet used.

thanks for reporting! we should also start ot use `rename.nix` features...

https://hydra.nixcloud.io/job/nixcloud-webservices/release-18.03/manual/latest/download/1

see

https://hydra.nixcloud.io/build/600/download/1/nixcloud-webservices/#opt-nixcloud.email.enableTLS
