### ISSUE TITLE
Secure POP not activated

### ISSUE THREAD

**Issue by leenaars** [nixcloud/nixcloud-webservices#3]
The Secure (TLS) version of POP normally runs on port 995, and allows direct connection over TLS rather than StartTLS (which can be MitM). The mail abstraction does yet seem to run this?

**Comment by uwap** [comment]
You are absolutely right. I will change this later. Thanks!

**Comment by leenaars** [comment]
BTW: thanks for the awesome work.

**Comment by uwap** [comment]
Dovecot2 uses pop3s and imaps on default. It doesn't seem to use the different ports though. @leenaars any thought on this?
