### ISSUE TITLE
nixcloud.email: example config runs VM test when built 

### ISSUE THREAD

**Issue by erictapen** [nixcloud/nixcloud-webservices#30]
This is my host config:

```nix
{ config, pkgs, ... }:
{

  nixcloud.email= {
    enable = true;
    domains = [ "erictapen.de" ];
    ipAddress = "REDACTED";
    ip6Address = "REDACTED";
    hostname = "mail.erictapen.de";
    enableSpamassassin = false;

    users = [
      { name = "mail"; domain = "erictapen.de"; password = "{PLAIN}passpass"; }
    ];
  };

}

```

I'm on `nixos-18.03` and `nixcloud-webservices` 8c9a23046406b4319f0a08d727183c5f03018059.

When deploying this, `vm-test-run-email` is built. This is annoying, as it takes alot of resources on my laptop. I there a reason for it?

**Comment by qknight** [comment]
just set `nixcloud.tests.enable = false;` to disable the tests. an alternative would be to use the newly introduced channels, see https://github.com/nixcloud/nixcloud-webservices#using-nixcloud-webservices

**Comment by qknight** [comment]
btw, we have to use the tests to make sure that the nixpkgs used don't screw our infrastrucutre.

**Comment by erictapen** [comment]
Okay, thanks, `nixcloud.tests.enable = false;` did the job. From a user perspective I'd probably prefered to have the testing being opt-in.
