### ISSUE TITLE
nixcloud.TLS cert owner option

### ISSUE THREAD

**Issue by fgaz** [nixcloud/nixcloud-webservices#34]
Most services do not run as root, but the certs are root-owned with permissions 0700

**Comment by fgaz** [comment]
Yes, that would help!
I'm running a mumble server (murmur) with this configuration:
```nix
{ config, lib, pkgs, ... }:

let
  domain = "my.domain.here";
in {
  nixcloud.TLS.certs.${domain} = {
    mode = "ACME";
    restart = [ "murmur.service" ]; # maybe restart is too much and reload is sufficient
  };

  services.murmur = {
    enable = true;
    password = "oh god why is this in a plaintext config file";
    sslCert = config.nixcloud.TLS.certs.${domain}.tls_certificate;
    sslKey  = config.nixcloud.TLS.certs.${domain}.tls_certificate_key;
  };
  systemd.services.murmur.after = [ "nixcloud.TLS-certificates.target" ];
  systemd.services.murmur.wants = [ "nixcloud.TLS-certificates.target" ];
}
```

Murmur silently (!) falls back to a self-signed cert if it can't read the provided one.

Radicale should also have this problem, but I have yet to set it up.

**Comment by qknight** [comment]
@fgaz nearly have this feature ready. needs some more testing but the code looks already promising:
https://github.com/nixcloud/nixcloud-webservices/tree/cert-user-groups

**Comment by qknight** [comment]
my config looks like this:

```
  nixcloud.TLS.certs."nix.lt" = {
    mode = "ACME";
    restart = [ "murmur.service" ]; # maybe restart is too much and reload is sufficient
    users = [ "murmur" ];
  };

  services.murmur = {
    enable = true;
    password = "oh god why is this in a plaintext config file";
    sslCert = config.nixcloud.TLS.certs."nix.lt".tls_certificate;
    sslKey  = config.nixcloud.TLS.certs."nix.lt".tls_certificate_key;
  };
  systemd.services.murmur.after = [ "nixcloud.TLS-certificates.target" ];
  systemd.services.murmur.wants = [ "nixcloud.TLS-certificates.target" ];


```

**Comment by qknight** [comment]
@fgaz some updates:

* fixed a permission bug
* refactored 'cert' into 'identifier'
* tested all 3 modes manually using 'murmur'

only one bug is left, when a user is not listed in users.groups anymore it still remains in `/etc/group` and i don't understand why. maybe a nixos bug and i will file this later.

will push these changes in nixcloud-webservices soon.

**Comment by qknight** [comment]
this feature is live with https://github.com/nixcloud/nixcloud-webservices/commit/7335d8e69121f99da8862e404987c9b54631dfe4

@fgaz please report in this issue if you still find issues and reopen!

**Comment by fgaz** [comment]
It works! Thanks for the fix!

I just had to force a cert renew since the permissions were still `rwx------`, but this shouldn't be a problem for new users.
