### ISSUE TITLE
Add extraConfig option for dovecot2

### ISSUE THREAD

**Issue by fgaz** [nixcloud/nixcloud-webservices#39]
I have a lot of folders and I use IDLE, so I need a high mail_max_userip_connections, but there's no way to add it to dovecot2's config without editing nixcloud-webservices

**Comment by qknight** [comment]
can't you just write this code anywhere in your configuration.nix?


```
      services.dovecot2.extraConfig = ''
        "mail_debug = yes"
      '';
```

**Comment by fgaz** [comment]
Oops, yeah, I can. I completely forgot about the automatic merging.

Thanks and sorry for wasting your time!
