### ISSUE TITLE
allowPing setting

### ISSUE THREAD

**Issue by leenaars** [nixcloud/nixcloud-webservices#43]
The ping setting for the mail module causes conflicts with other modules... seems unlikely to be essential to the functioning of the mail module, and could perhaps be removed?

error: The option `networking.firewall.allowPing' has conflicting definitions, in `/nix/store/1ddrbljzx3i7j8y5yyy495nb97q7xdrd-nixcloud-webservices/nixcloud-webservices/modules/services/email/nixcloud-email.nix' and `/etc/nixos/redacted.nix'

**Comment by qknight** [comment]
fixed in e48ea15eda561e3c28f12df63f8220fe95e5b41d

thanks for pointing this out!
