### ISSUE TITLE
nixcloud-webservices 18.09 doesn't seem to enforce nixos/nixpkgs 18.09

### ISSUE THREAD

**Issue by eliasp** [nixcloud/nixcloud-webservices#48]
Quoting comment from chat:
> today, I finally also upgraded my personal mailserver to nixcloud-webservices/email 18.09 with our new TLS stack and stumbled upon an issue, of which I'm not sure, whether it can be prevented properly/Nix-ish…
…I switched my `nixcloud-webservices` channel from `18.03` to `18.09`, but forgot to do the same for my regular nixos channel and `stateVersion`, which resulted in `nixcloud.TLS` pulling in an ancient `lego` release which ended up failing due to a bug which is fixed in `18.03`…
…shouldn't `nixos-webservices-18.09` somehow enforce the proper/required release of NixOS/nixpkgs/stateVersion?

**Comment by qknight** [comment]
see this commit: https://github.com/nixcloud/nixcloud-webservices/commit/7cca6d464341c05f0e125e354273c590bba4a59b

it enforces that now! thanks for pointing out.
