### ISSUE TITLE
Firewall ports open for reverse proxy

### ISSUE THREAD

**Issue by leenaars** [nixcloud/nixcloud-webservices#5]
Currently, the user needs to indicate manually in the configuration that port 80 and port 443 need to be opened. However, if the reverse proxy is used, this implies that those ports are to be opened.

**Proposed solution:** 
Add ports 80 and 443 firewall rules when reverse proxy is active.

**Comment by qknight** [comment]
this has been fixed in  6d83eea58a04da75bb14714a3ccd9efbc87cea1f and we now add the respective ports to the firewall by default as wished.
