### ISSUE TITLE
Non-root ownership of state dirs

### ISSUE THREAD

**Issue by leenaars** [nixcloud/nixcloud-webservices#6]
By default, the state directories are owned by root.
This seems wrong, these should be owned by the owner of the process that is supposed to write in those directories.

**Proposed solution: **
At creation of state directory, assign rights to the right owner. Use setgid.

**Comment by qknight** [comment]
your assumption is right. looking into this.

**Comment by qknight** [comment]
@leenaars can't reproduce this with the leaps service. how can i reproduce your problem? are you using something else than the leaps service like the `/root/nixcloud.monitoring-server/pkgs/nixcloud-webservices/lib/make-webservice.nix` mechanism?

**Comment by aszlig** [comment]
I'd suggest a more generic solution where within instances you have a `createDirectories` option that is responsible for creating all sorts of directories in one place, especially because creating directories is something that's quite common for a lot of services.

**Comment by qknight** [comment]
@leenaars aszlig and me are currently looking into alternatives to the current concept of using the nixos abstraction to create the homedir. we consider two options:

* requireDirectory: which uses `chmod g+s /some/dir`
* requireDirector: which uses POSIX ACL commands

**Comment by qknight** [comment]
@aszlig irgend ein zeitlicher plan hier?
