### ISSUE TITLE
nixos-19.09: containers test fails

### ISSUE THREAD

**Issue by qknight** [nixcloud/nixcloud-webservices#66]
fails with:

client# [  920.629694] systemd[1]: Started Cleanup of Temporary Directories.
mail1: running command: nc -z localhost 80
mail1: exit status 1
(0.01 seconds)
mail1: running command: nc -z localhost 80
mail1: exit status 1
(0.01 seconds)
mail1: running command: nc -z localhost 80
mail1: exit status 1
(0.01 seconds)
mail1: running command: nc -z localhost 80
mail1: exit status 1
(0.01 seconds)
mail1: running command: nc -z localhost 80
mail1: exit status 1
(0.01 seconds)
mail1: running command: nc -z localhost 80
mail1: exit status 1
(0.01 seconds)
mail1: running command: nc -z localhost 80
mail1: exit status 1
(0.01 seconds)
mail1: running command: nc -z localhost 80
mail1: exit status 1
(0.01 seconds)
mail1: running command: nc -z localhost 80
mail1: exit status 1
(0.01 seconds)
mail1: running command: nc -z localhost 80
mail1: exit status 1
(0.01 seconds)
mail1: running command: nc -z localhost 80
mail1: exit status 1
(0.01 seconds)
mail1: running command: nc -z localhost 80
mail1: exit status 1
(0.01 seconds)
(908.57 seconds)
The nixcloud test 'email' has failed with error 'action timed out after -1 seconds at /nix/store/f053vwv6hdkhl7xxaqcx1dmb5gqd88s0-nixos-test-driver/lib/perl5/site_perl/Machine.pm line 247, <__ANONIO__> line 1246.' but in case the machine was too slow (virtualized, not enough ram, too much cpu load, etc) then you can also disable the tests by adding 'nixcloud.tests.enable = false;' to your /etc/nixos/configuration.nix and still use our software.
cleaning up
killing client (pid 6)
killing mail2 (pid 18)
killing mail1 (pid 30)
killing dns (pid 42)
(0.00 seconds)
Attempt to end element "nest" with "logfile" tag at /nix/store/f053vwv6hdkhl7xxaqcx1dmb5gqd88s0-nixos-test-driver/lib/perl5/site_perl/Logger.pm line 28.
END failed--call queue aborted, <__ANONIO__> line 1246.
vde_switch: EOF on stdin, cleaning up and exiting
vde_switch: Could not remove ctl dir '/build/vde1.ctl': Directory not empty
builder for '/nix/store/mc7pj1z8g1x25s0ip2c5adzg45g1fmvd-vm-test-run-email.drv' failed with exit code 22
error: build of '/nix/store/mc7pj1z8g1x25s0ip2c5adzg45g1fmvd-vm-test-run-email.drv' failed

**Comment by griff** [comment]
I just came across this myself and it seems that `nixcloud.email.webmail.enable` can't be true  unless `nixcloud.email.enableTLS` is also true and that is the case in the email test.

Have the tests even been run before webmail was merged?
