### ISSUE TITLE
20.09: preliminary self-signed certificates fail to generate

### ISSUE THREAD

**Issue by fgaz** [nixcloud/nixcloud-webservices#72]
```
[...]
Oct 29 13:58:26 nixos nixcloud.TLS-acmeSuppliedPreliminary-<snip>-start[528]: Done creating a self signed certificate
Oct 29 13:58:26 nixos nixcloud.TLS-acmeSuppliedPreliminary-<snip>-post-start[728]: cp: cannot stat '/tmp/server.key': No such file or directory
```

Really weird. The ExecStart didn't fail, so server.key should be there

**Comment by fgaz** [comment]
Wild guess: when [PermissionsStartOnly was deprecated](https://github.com/NixOS/nixpkgs/issues/53852), it was changed to have the same semantics as adding [the + prefix](https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStart=) to everything except ExecStart. This would mean that the PrivateTmp (acmeSuppliedPreliminary sets it in addition to PermissionsStartOnly) is now ExecStart-specific, breaking the service

**Comment by fgaz** [comment]
If that's the case, this could be fixed by using [`RuntimeDirectory`](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#RuntimeDirectory=) or [tmpfiles](https://www.freedesktop.org/software/systemd/man/tmpfiles.d.html#) instead.

**Comment by fgaz** [comment]
Yes, setting `RuntimeDirectory` and using `$RUNTIME_DIRECTORY` instead of `/tmp` in `services/TLS` does the trick! I'll open a pr

**Comment by nh2** [comment]
@fgaz What came of this?

**Comment by fgaz** [comment]
@nh2 I fixed it but forgot to send the patch. Thanks for reminding me, here it is: #74
